local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Instances = require(ReplicatedStorage.Instances)
local workspace = Instances:Register(workspace)
local BaseParts = workspace:GetDescendantsWhichAre("BasePart")
print(BaseParts)